apiVersion: v1
kind: Secret
metadata:
  labels:
    troubleshoot.sh/kind: preflight
  name: "{{ .Release.Name }}-preflight-config"
stringData:
  preflight.yaml: |
    apiVersion: troubleshoot.sh/v1beta2
    kind: Preflight
    metadata:
      name: node-status-check
    spec:
      analyzers:
        - nodeResources:
            checkName: Node status check
            outcomes:
              - fail:
                  when: "nodeCondition(Ready) == False"
                  message: "Not all nodes are online."
              - fail:
                  when: "nodeCondition(Ready) == Unknown"
                  message: "Not all nodes are online."
              - pass:
                  message: "All nodes are online."

